config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  get 'lessons/index'
  # get '/projects/:project_id/lessons(.:format)', to: redirect('/projects/:project_id(.:format)')

  constraints(SubdomainPresent) do
    
    devise_for :users, :controllers => { :registrations => "registrations" }


    devise_scope :user do
      # get "login", to: "devise/sessions#new"
      # get "logout", to: "devise/sessions#destroy"
      get "register", to: "devise/registrations#new"
    end
    
    # resources :users, only: :index
    resources :subscribe
    resources :users
    resources :projects do
      resources :lessons
    end
    
    resources :accounts 

    root 'accounts#index', as: :subdomain_root
  end
  
  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create, :edit]
  end
end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController
  before_filter :authenticate_user!

  def new
  end

  def update
    #gets the credit card details submitted in the form
    token = params[:stripeToken]

    #create a customer
    customer = Stripe::Customer.create(
      card: token,
      plan: 1095,
      email: current_user.email
    )

    current_user.subscribed = true
    current_user.stripeid = customer.id
    current_user.save


    redirect_to projects_path, notice: "Your subscription was set up successfully! Happy learning!"

  end



end

app/helpers/subscribe_helper.rb
module SubscribeHelper
end

app/views/subscribe/_form.html.erb
<%= form_tag subscribe_path(1), method: :put do %>


<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="2900"></script><span> $29 per month, cancel at any time.</span>
<% end %>       

app/views/subscribe/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 panel panel-default form-style">
            <div class="panel-body">
                <h2>Final Signup Step</h2>
                <h4>This is the final step to give you full access to <%= current_account.subdomain.capitalize %></h4>  
                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>