config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  get 'lessons/index'
  # get '/projects/:project_id/lessons(.:format)', to: redirect('/projects/:project_id(.:format)')

  constraints(SubdomainPresent) do
    
    devise_for :users, :controllers => { :registrations => "registrations" }


    devise_scope :user do
      # get "login", to: "devise/sessions#new"
      # get "logout", to: "devise/sessions#destroy"
      get "register", to: "devise/registrations#new"
    end
    
    # resources :users, only: :index
    resources :subscribe
    resources :users
    resources :projects do
      resources :lessons
    end
    
    resources :accounts 

    root 'accounts#index', as: :subdomain_root
  end
  
  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create, :edit]
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :account
    has_many :lessons

    validates :name, presence: true, uniqueness: true
    validates :subtitle, presence: true
    validates :description, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @projects = current_account.projects.all
  end

  def show
    @project = current_account.projects.find(params[:id])
  end

  def new
    @project = current_account.projects.new
  end

  def create
    @project = current_account.projects.build(project_params)
    if @project.save
      redirect_to project_path(@project), notice: "Project created"
    else
      render :new
    end
  end

  def edit
    @project = current_account.projects.find(params[:id])
  end

  def update
    @project = current_account.projects.find(params[:id])

    if @project.update(project_params)
      redirect_to projects_path, notice: "Project updated"
    else
      render :edit
    end
  end

  def destroy
    @project = current_account.projects.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :subtitle, :description)
  end



end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project,
                    wrapper_mappings: { boolean: :vertical_boolean }) do |f| %>

  <%= f.input :name %>
  <%= f.input :subtitle %>
  <%= f.input :description %>
  
  <%= f.button :submit, class: 'btn-material-red' %>
<% end %>

app/views/projects/edit.html.erb
<div class="container">
	<div class="row">
	<div class="col-md-6 col-md-offset-3 panel panel-default form-style">
			<div class="panel-body">
				<h2>Update Course</h2>
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="col-md-12 form-style panel panel-body">

    <% if @projects.count == 0 %>

    <ul class="list-group">
      <li class="list-group-item">No entries yet!</li>
    </ul>

    <% else %>


    <% @projects.each do |project| %>
    <h3>
      <%= link_to project.name, project_path(project) %>
      <small><%= project.subtitle %></small>
      <div class="pull-right">
        <%= link_to edit_project_path(project), class: "icon-link" do %>
        <small><i class="glyphicon glyphicon-cog"></i></small>
        <% end %>
        <%= link_to project_path(project), method: :delete do %>
        <small><i class="glyphicon glyphicon-trash"></i></small>
        <% end %>
      </div>
    </h3>
    <p>
      <%= project.description %>
    </p>
    <% end %>

    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 panel panel-default form-style">
			<div class="panel-body">
				<h2>New Course</h2>
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/projects/show.html.erb
<div class="course-path-header">
  <div class="container">
    <div class="col-md-9">
      <h3><%= @project.name %></h3>
    </div>
    <div class="col-md-3 course-new-button">
      <%= link_to 'New Lesson', new_project_lesson_path(@project), class: "btn btn-success pull-right right-button" %>
    </div>
  </div>
</div>

<div class="container form-style">

  <div class="col-md-8 col-md-offset-2">
    <h3><small> Lessons for <%= @project.name %> </small></h3>

    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <% @project.lessons.each do |lesson| %>
            <tr>
              <!-- The Lesson Name and Link to the Lesson -->
              <td><%= link_to lesson.name, project_lesson_path(@project, lesson) %></td>
              <td><%= lesson.description %>
              <!-- Edit and Delete buttons -->
                <div class="pull-right">
                  <%= link_to edit_project_lesson_path(@project, lesson), class: "icon-link" do %>
                    <small><i class="glyphicon glyphicon-cog"></i></small>
                  <% end %>
                  <%= link_to project_lesson_path(@project, lesson), method: :delete do %>
                    <small><i class="glyphicon glyphicon-trash"></i></small>
                  <% end %>
                </div>  
              </td>

            </tr>

            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>

</div>