config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  get 'lessons/index'
  # get '/projects/:project_id/lessons(.:format)', to: redirect('/projects/:project_id(.:format)')

  constraints(SubdomainPresent) do
    
    devise_for :users, :controllers => { :registrations => "registrations" }


    devise_scope :user do
      # get "login", to: "devise/sessions#new"
      # get "logout", to: "devise/sessions#destroy"
      get "register", to: "devise/registrations#new"
    end
    
    # resources :users, only: :index
    resources :subscribe
    resources :users
    resources :projects do
      resources :lessons
    end
    
    resources :accounts 

    root 'accounts#index', as: :subdomain_root
  end
  
  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create, :edit]
  end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        # concat content_tag(:div, msg, id: "flash_#{name}")
        concat content_tag(:div, msg, class: "alert alert-success")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if current_account %>
      <%= current_account.subdomain %>
    <% else %>
       Sensei
    <% end %>
  </title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

 <nav class="navbar navbar-material-custom-grey">
  <div class="navbar-header">
    <% if current_account %>
      <%= link_to image_tag(current_account.school_logo_attachments, border: 0), subdomain_root_path, class: "school-logo" %>
      <%= link_to current_account.subdomain.capitalize , root_path, class: "school-title" %>
    <% else %>
      <%= link_to 'Sensei', root_path, class: 'navbar-brand' %>
    <% end %>
  </div>

  <div class="pull-right right-button">
  <% if user_signed_in? %>
    <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'btn btn-default navbar-btn' %>
  </div>

  <ul class="nav navbar-nav navbar-right">
  <li><%= link_to '+ New Course', new_project_path %></li>                 
    <li><%= link_to 'My Courses', projects_path %></li> 
    <li><%= link_to 'Users', users_path %></li>
    <%# binding.pry %>
    <li><%= link_to 'School Settings', edit_account_path(current_account) %></li>
  </ul>

  <div class="pull-right right-button">
  <% elsif !user_signed_in? && current_account %>
      <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
  <% else %>    
      <%= render link_to 'Sign Up', new_user_registration_path, class: 'btn btn-success navbar-btn' if !subdomain_root_path %>
  </div>
  <% end %>
</div>
</nav>

<div class="page-wrap">

  <%= yield %>

</div>



</body>
</html>