config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  get 'lessons/index'
  # get '/projects/:project_id/lessons(.:format)', to: redirect('/projects/:project_id(.:format)')

  constraints(SubdomainPresent) do
    
    devise_for :users, :controllers => { :registrations => "registrations" }


    devise_scope :user do
      # get "login", to: "devise/sessions#new"
      # get "logout", to: "devise/sessions#destroy"
      get "register", to: "devise/registrations#new"
    end
    
    # resources :users, only: :index
    resources :subscribe
    resources :users
    resources :projects do
      resources :lessons
    end
    
    resources :accounts 

    root 'accounts#index', as: :subdomain_root
  end
  
  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create, :edit]
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
    RESTRICTED_SUBDOMAINS = %w[www]

    has_many :projects
    belongs_to :owner, class_name: 'User'
    validates :owner, presence: true

    validates :subdomain, presence: true,
                            uniqueness: { case_sensitive: false },
                            format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters' },
                            exclusion: { in: RESTRICTED_SUBDOMAINS, message: 'restricted' }


    accepts_nested_attributes_for :owner

    before_validation :downcase_subdomain

    mount_uploader :school_logo_attachments, SchoolLogoAttachmentsUploader
    mount_uploader :school_background_attachments, SchoolBackgroundAttachmentsUploader

    private

        def downcase_subdomain
            self.subdomain = subdomain.try(:downcase)
        end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:index, :new, :create, :show]


  def new
    @account = Account.new
    @account.build_owner
  end

  def create
    @account = Account.new(account_params)
    if @account.valid?
        Apartment::Tenant.create(@account.subdomain)
        Apartment::Tenant.switch(@account.subdomain)
        @account.save
        redirect_to new_user_session_url(subdomain: @account.subdomain)
    else
        render action: 'new'
    end
  end

  def index
    @accounts = Account.all
  end

  def edit
      @account = current_account
  end

  def show
    redirect_to subdomain_root_path
  end

  def update
    @account = current_account
     
    if @account.update(account_params)
        redirect_to subdomain_root_path, notice: "Your school has been updated"
    else 
        render :edit
    end
  end

  private
  
  def account_params
    # binding.pry
    params.require(:account).permit(:subdomain, :tagline, :description, :school_logo_attachments, :school_background_attachments, owner_attributes: [:name, :email, :password, :password_confirmation]) 
  end


end

app/views/accounts/_form.html.erb
<%= simple_form_for(current_account, wrapper_mappings: { boolean: :vertical_boolean }, html: {multipart: true}) do |f| %>

  <%= f.input :tagline %>
  <%= f.input :description %>
  <div class="btn btn-info btn-file file-btn-edit">
  <%= f.input :school_logo_attachments %>
  </div>
  <div class="btn btn-warning btn-file file-btn-edit">
  <%= f.input :school_background_attachments %>
  </div>
  <%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/accounts/create.html.erb
<h1>Accounts#create</h1>
<p>Find me in app/views/accounts/create.html.erb</p>

app/views/accounts/edit.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default form-style">
    <div class="panel-body">
        <h2>Update School Details</h2>
        <%= render 'form' %>
    </div>
</div>

app/views/accounts/index.html.erb
<%= stylesheet_link_tag 'accounts' %>


<div class="jumbotron jumbotron-front-page" style="background-image: url('<%= image_path(current_account.school_background_attachments) %>');">
  <div class="container front-page">
  <% if current_account.school_logo_attachments == nil %>
      <% else %>
    <%= image_tag current_account.school_logo_attachments, class: "school-logo school-logo-header" %>
    <% end %>
  </div>
</div>

<div class="container">

  <div class="row">

    <div id="home-body">
      <span class="subdomain-title"><h1>Welcome to <%= current_account.subdomain %></h1></span>
      <span class="lead">
        <% if current_account.tagline == nil %>
          <p class="lead">Go to School Settings to add in your school's tagline here.<p>
        <% else %>
          <p class='lead'><%= current_account.tagline %></p>
        <% end %>
      </span>

      <div id="about">
        <h3> About <%= current_account.subdomain %></h3>
        <% if current_account.description == nil %>
        <p class="lead">Go to School Settings to add in details about your school.</p>
        <% else %>
        <p class='lead'><%= current_account.description %></p>
        <% end %>

      </div>

    </div>
  </div>

  <div class="row">
    <h3>The courses</h3>
    <% current_account.projects.each do |project| %>
    <div class="col-md-6">
      <div class="project_box panel panel-default">
      <% if user_signed_in? %>
        <%= link_to project.name, project_path(project) %>
        <% else %>
        <%= project.name %>
        <% end %>
        <%= project.subtitle %>

        <% if current_account.projects.count == 0 %>
          <%= link_to 'New Course', new_project_path, class: "btn btn-primary" %>
        <% end %>

      </div>
    </div>
    <% end %>
  </div>

app/views/accounts/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default form-style">
  <div class="panel-body">
    <h2>Create a School</h2>

    <%= simple_form_for @account do |f| %>

      <%= f.fields_for :owner do |o| %>

        <%= o.input :name, class: 'form-control', data: { toggle: 'tooltip', trigger: 'hover', placement: 'left' }, title: "Enter the first and last name of the administrator you'd like to have." %>
        <%= o.input :email, data: { toggle: 'tooltip', placement: 'top' }, title: "Enter the email you'd like to use for the administrator for your school" %>
        <%= o.input :password %>
        <%= o.input :password_confirmation %>

      <% end %>
    

      <%= f.input :subdomain do %>
        <div class="input-group">
          <%= f.input_field :subdomain, class: 'form-control', data: { toggle: 'tooltip', placement: 'left' }, title: "Enter your school name to be the subdomain" %>
          <span class="input-group-addon">.getsensei.net</span>
        </div>
      <% end %>

      <%= f.button :submit, class: 'btn-primary' %>
      
    <% end %>
  </div>
</div>